In [1]:
import pandas as pd
import mysql.connector

In [2]:
df = pd.read_csv('../data/saas_funnel_raw.csv')
df.head()

,user_id,signup_date_raw,acquisition_channel,country_raw,device_raw,age,marketing_spend,session_count,visited_site,signed_up,completed_onboarding,onboarding_date_raw,activated_core_feature,activation_date_raw,started_trial,trial_start_date_raw,converted_to_paid,conversion_date_raw,plan_type,active_after_30_days
0,102181,19-03-2024,Paid Ads,Aus,Mobile Phone,23.0,0.92,7.0,Yes,Yes,Yes,"Mar 22, 2024",No,NaN,No,NaN,No,NaN,Pro,NaN
1,106021,23-11-2025,Paid Ads,United states,Desk top,43.0,12.91,5.0,Yes,Yes,Yes,24-11-2025,Yes,26-11-2025,Yes,"Dec 04, 2025",Yes,"Dec 06, 2025",Pro,No
2,102345,27-07-2025,Referral,U.S.A,NaN,32.0,0.00,5.0,Yes,Yes,No,NaN,No,NaN,No,NaN,No,NaN,Basic,NaN
3,106968,19-07-2024,Social Media,America,Desk top,38.0,0.00,6.0,Yes,Yes,No,NaN,No,NaN,No,NaN,No,NaN,Pro,NaN
4,105206,17-09-2025,Email Campaign,Germany,mobile,NaN,NaN,9.0,Yes,Yes,Yes,09/19/2025,Yes,22-09-2025,Yes,26-09-2025,No,NaN,NaN,NaN

In [3]:
len(df)

7381

In [4]:

df = df.where(pd.notnull(df), None)
df = df.astype(object).where(pd.notnull(df), None)  # ← add this line

In [5]:
df.head()

,user_id,signup_date_raw,acquisition_channel,country_raw,device_raw,age,marketing_spend,session_count,visited_site,signed_up,completed_onboarding,onboarding_date_raw,activated_core_feature,activation_date_raw,started_trial,trial_start_date_raw,converted_to_paid,conversion_date_raw,plan_type,active_after_30_days
0,102181,19-03-2024,Paid Ads,Aus,Mobile Phone,23.0,0.92,7.0,Yes,Yes,Yes,"Mar 22, 2024",No,None,No,None,No,None,Pro,None
1,106021,23-11-2025,Paid Ads,United states,Desk top,43.0,12.91,5.0,Yes,Yes,Yes,24-11-2025,Yes,26-11-2025,Yes,"Dec 04, 2025",Yes,"Dec 06, 2025",Pro,No
2,102345,27-07-2025,Referral,U.S.A,None,32.0,0.0,5.0,Yes,Yes,No,None,No,None,No,None,No,None,Basic,None
3,106968,19-07-2024,Social Media,America,Desk top,38.0,0.0,6.0,Yes,Yes,No,None,No,None,No,None,No,None,Pro,None
4,105206,17-09-2025,Email Campaign,Germany,mobile,None,None,9.0,Yes,Yes,Yes,09/19/2025,Yes,22-09-2025,Yes,26-09-2025,No,None,None,None

In [6]:
# Connect to MySQL
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='1234',
    database='saas_funnel'
)

In [7]:
cursor = conn.cursor()
print("Connected to MySQL successfully")

# Insert every row into MySQL
insert_query = """
INSERT INTO saas_funnel_raw (
    user_id, signup_date_raw, acquisition_channel, country_raw,
    device_raw, age, marketing_spend, session_count, visited_site,
    signed_up, completed_onboarding, onboarding_date_raw,
    activated_core_feature, activation_date_raw, started_trial,
    trial_start_date_raw, converted_to_paid, conversion_date_raw,
    plan_type, active_after_30_days
) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
"""


for index, row in df.iterrows():
    cursor.execute(insert_query, tuple(row))

conn.commit()
print("All rows inserted successfully")

# Verify count
cursor.execute("SELECT COUNT(*) FROM saas_funnel_raw")
count = cursor.fetchone()
print("Total rows in MySQL:", count[0])

cursor.close()
conn.close()

Connected to MySQL successfully
All rows inserted successfully
Total rows in MySQL: 7381